server:
  port: 8081

app:
  cors:
    allowed-origins: http://localhost:3000,http://127.0.0.1:3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

jwt:
  secret: mySuperSecretKeyForJwtSigningshdfgkjsdgjkbsdfg
  expiration: 3600000
