server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

jwt:
  secret: mySuperSecretKeyForJwtSigningshdfgkjsdgjkbsdfg
  expiration: 3600000 
