server:
  port: 8081

app:
  cors:
    allowed-origins: http://localhost:3000

spring:
  application:
    name: finance-tracker

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
